### ISSUE TITLE
Large Cache Size with the Waymo Open Motion Dataset

### ISSUE THREAD

**Issue by pschafhalter** [vita-epfl/UniTraj#18]
Hello and thank you for releasing this repository.

I'm trying to train motion prediction models using the Waymo Open Motion Dataset and found that the cache size is very large. When training Autobot, the size of the `cache_autobot` folder is 1.3 terabytes – 3.7x larger than the original dataset size of ~350 GB. I was unable to train Wayformer because the cache size grew to several terabytes and filled the entire disk storage.

Is there some way to reduce the cache size? How much storage is needed to train Wayformer on the Waymo Open Motion Dataset?

For context, I generated the dataset with the following command:
```bash
python -m scenarionet.convert_waymo \
   -d waymo \
   --raw_data_path=waymo_open_dataset_motion_v_1_2_1/uncompressed/scenario/training \
   --num_workers=64
```

My`config.yaml for training Autobot is as follows:
```yaml
# exp setting
exp_name: 'autobot' # name that will be used in wandb
ckpt_path: null  # checkpoint path, used for evaluation
seed: 42 # random seed
debug: False # debug mode, will use cpu only
devices: [ 0, 1, 2, 3, 4, 5, 6, 7 ] # gpu ids

# data related
load_num_workers: 8 # number of workers for loading data
train_data_path: [ "data_samples/waymo" ] # list of paths to the training data
val_data_path: ["data_samples/waymo_val"] # list of paths to the validation data
max_data_num: [ 10000000 ] # maximum number of data for each training dataset
past_len: 10 # history trajectory length, 2.1s
future_len: 80 # future trajectory length, 6s
object_type: [ 'VEHICLE', 'PEDESTRIAN', 'CYCLIST'] # object types included in the training set
line_type: [ 'lane','stop_sign','road_edge','road_line','crosswalk','speed_bump'] #, 'driveway' ] # line type to be considered in the input
masked_attributes: [ 'z_axis', 'size' ] # attributes to be masked in the input
trajectory_sample_interval: 1 # sample interval for the trajectory
only_train_on_ego: False # only train on AV
center_offset_of_map: [ 30.0, 0.0 ] # center offset of the map
use_cache: False # use cache for data loading
overwrite_cache: False # overwrite existing cache
store_data_in_memory: False # store data in memory

# official evaluation
# nuscenes_dataroot: '/mnt/nas3_rcp_enac_u0900_vita_scratch/datasets/Prediction-Dataset/nuscenes/nuscenes_root'
eval_nuscenes: False # whether to evaluate with nuscenes evaluation tool
eval_waymo: False # whether to evaluate with waymo evaluation tool

defaults:
  - method: autobot
```
